In [1]:
# Programming is a powerful tool you can use to solve all kinds of problems.


In [3]:
# print hello word statement
print('Hello World')

Hello World


In [4]:
# two line seperated using\n
print("My Name is Rutuja\n I am From Nashik")

My Name is Rutuja
 I am From Nashik


In [5]:
# you can also write triple quote string
print("""This is the strangest way to print over multiple lines i know""")

This is the strangest way to print over multiple lines i know


In [15]:
# add two string
print("here is a string " + "Here is more")

here is a string Here is more


In [16]:
# trinting method how single and double quate use
print('here is a double quate ",'+ " here is a single quate'.")

here is a double quate ", here is a single quate'.


In [14]:
# code method use of \
print("or you can just do this \" does that work")

or you can just do this " does that work


In [17]:
print("can i print just a \ on the screen")

can i print just a \ on the screen


In [20]:
# i am inserting a \\ so the \ appers correctly in the string
print("But what if i want \\news") 

But what if i want \news


In [22]:
print('It\'s a small world')

It's a small world


In [24]:
# Exercise print a poem

In [26]:
print("There once was a movie star icon\n who prefferred to sleep with the light on.\n They learned how to code\n a device that sure glowed\n and lit up the night using python!")

There once was a movie star icon
 who prefferred to sleep with the light on.
 They learned how to code
 a device that sure glowed
 and lit up the night using python!


In [27]:
 # String Variable

In [34]:
name = input("What is Your Name? ")

What is Your Name? Rutuja


In [35]:
# here name is variable
print(name)

Rutuja


In [36]:
name1 = "Mary"

In [38]:
print(name1)

Mary


In [ ]:
# Variables rule and working with variables.
# Rules
 # 1)  

In [1]:
dic1 = {1.0:'V1', 2.0:'V2', 3.0:'V3'}
dic1

{1.0: 'V1', 2.0: 'V2', 3.0: 'V3'}

In [2]:
dic2 = {1+1:'V1', 3/1:'V2','A'+'B':'V3'}
dic2

{2: 'V1', 3.0: 'V2', 'AB': 'V3'}

In [3]:
dic3 = {(1,2): 'V1',(2,3):'V2', (3,4): "v3"}
dic3

{(1, 2): 'V1', (2, 3): 'V2', (3, 4): 'v3'}

In [4]:
dic = {[1,2,4]:5}

TypeError: unhashable type: 'list'

In [25]:
l = [1,4,6] 
# write program for print even
for i in l:
    if (i%2) == 0:print(i)

4
6


In [10]:
l = [1,4,6]
x = [i for i in l if (i%2) == 0]
x

[4, 6]

In [17]:
n = 72
while n%2 == 0:
    n = n/2
    print(n)

36.0
18.0
9.0


In [18]:
n = 72
while True:
    n = n/2
    if n%2!=0:
        print(n)
        break


9.0


In [19]:
l = [64,128,73,25,0,-3,-74]
n = 165
# find all numbers in l greater than n.
i = 0
while i < len(l):
    if l[i] > n:
        print(l[i])
    i = i+1


In [20]:
for i in range(1, 11):
 
    # If i is equals to 6,
    # continue to next iteration
    # without printing
    if i == 6:
        continue
    else:
        # otherwise print the value
        # of i
        print(i, end=" ")


1 2 3 4 5 7 8 9 10 

In [24]:
a = "programming"
for i in a:
    if i =="p":
        continue
    else:
        print(i)


r
o
g
r
a
m
m
i
n
g


In [26]:
# Recursive function
def recursive_factorial(n):  
    if n == 1:  
        return n  
    else:  
        return n * recursive_factorial(n-1)


In [28]:
l=[64,128,73,25,0,-3,-74]
i=0
j=1
l1=[]
while(i<=len(l)-1):
    if(l[i] <= l[j]):
temp = l[i];
    l[i] = l[j];
    l[j] = temp;
    j=j+1  
    i=i+1
  

print(l)


IndentationError: expected an indented block (Temp/ipykernel_8252/3447133634.py, line 7)

In [1]:
class Book:
    def __init__(self,pages,price,author,ID,title):
        self.pages = pages
        self.price = price
        self.author = author
        self.ID =ID
        self.title = title
class BookStore:
    def __init__(self,objlist):
        self.objlist = objlist
    def findMinimumBookByid(self):
        lis1 = []
        for i in self.objlist:
            lis1.append(i.ID)
        lis1.sort()
        for j in self.objlist:
            if lis1[0]==j.ID:
                print(j.pages)
                print(j.price)
                print(j.author)
                print(j.ID)
                print(j.title)
        if lis1==None:
            return None
    def sortBookByid(self):
        lis2 = []
        for j in self.objlist:
            lis2.append(j.ID)
        lis2.sort()
        for i in lis2:
            print(i)
        if lis2 == None:
            return None
n = int(input())
objlist= []
for i in range (n):
    pages = int(input())
    price = int(input())
    author = input()
    ID = int(in


SyntaxError: invalid syntax (Temp/ipykernel_16108/1696637282.py, line 40)

In [13]:
import numpy as np

In [18]:
A = np.array([1,3,5], [3,4,6], [6,7,9])
A

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
A.shape

(3,)

In [9]:
A.shape = (1,3)

In [10]:
A

array([[1, 3, 5]])

In [11]:
A.reshape(-1,3)

array([[1, 3, 5]])

In [22]:
A = np.array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])
A

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
A.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.zeros(4)

array([0., 0., 0., 0.])

In [32]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
A = np.array([[1,2,3,2],[2,3,4,5],[4,5,7,5],[6,7,8,9]])
A


array([[1, 2, 3, 2],
       [2, 3, 4, 5],
       [4, 5, 7, 5],
       [6, 7, 8, 9]])

In [39]:
A[[1,2],[[2,3],1]]


C:\Users\DELL\AppData\Local\Temp/ipykernel_16108/3667089356.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  A[[1,2],[[2,3],1]]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [2]:
n =

IndentationError: expected an indented block (Temp/ipykernel_17600/4039768555.py, line 2)

In [4]:
# Q.1 print 10 natural number
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [2]:
i = 1
while (i<= 10):
    print(i)
    i = i+1

1
2
3
4
5
6
7
8
9
10


In [10]:
# q.2 program print n natural number
n = int(input("please enter a number"))
for i in range(1,n+1):
    print(i)

please enter a number15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [4]:
n = int(input("Enter a number: "))
i = 1
while(i<= n):
    print(i)
    i = i+1

Enter a number: 10
1
2
3
4
5
6
7
8
9
10


In [14]:
# Q.3 print first n natrural number in reverse order
for i in reversed(range(5)):
    print(i)
    

4
3
2
1
0


In [6]:
n = int(input('enter a number:'))
while (n>0):
    print(n)
    n = n-1

enter a number:10
10
9
8
7
6
5
4
3
2
1


In [15]:
list1 = [1, 2, 3, 4]
for i in reversed(list1):
    print(i)

4
3
2
1


In [17]:
number = int(input("Enter any Number: "))
i = number

print("List of Natural Numbers from {0} to 1 in Reverse Order: ".format(number))

while ( i >= 1):
    print (i, end = '  ')
    i = i - 1


Enter any Number: 10
List of Natural Numbers from 10 to 1 in Reverse Order: 
10  9  8  7  6  5  4  3  2  1  

In [19]:
# print sum of 1st n natural number
n = int(input('enter natural number: '))
sum = n*(n+1)/2
print(sum)

enter natural number: 6
21.0


In [9]:
n = int(input('enter a number'))
i = 1
sum = 0
while (i <= n):
    sum = sum + i
    i = i + 1
print('sum=' ,sum)

enter a number10
sum= 55


In [12]:
# print sum of square of n number
i = i + 1

In [14]:
# print sum of square of n number
n = int(input("enter a number :"))
sum = 0 
for in range(1,n+1):
    summ+= (i*i)
print("sum of square=",sum)

SyntaxError: invalid syntax (Temp/ipykernel_11980/2748768980.py, line 4)

In [24]:
N = int(input('enter a number: '))
sumVal = 0
for i in range(1, N+1):
    sumVal += (i*i)
print("Sum of squares = ", sumVal)


enter a number: 3
Sum of squares =  14
